name: decOM
channels:
  - conda-forge
  - defaults
  - tlemane
  - camiladuitama
dependencies:
  - colorama
  - numpy
  - pandas
  - plotly
  - dask
  - kmtricks
  - importlib_resources
  - argparse

