{% set name = "decom" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decOM-{{ version }}.tar.gz
  sha256: 332e16d66dd7b65d390f245802da19f525d25818d8d20b6a95613f9b56f5947d

build:
  entry_points:
    - decOM=decOM.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dask-core >=2021.12.0
    - importlib-resources >=5.4.0
    - python-kaleido
    - plotly >=5.5.0
    - python >=3.6

test:
  imports:
    - decOM
  commands:
    - pip check
    - decOM --help
  requires:
    - pip

about:
  home: https://github.com/CamilaDuitama/decOM
  summary: 'decOM: K-mer method for aOral metagenome decontamination'
  license: GPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CamilaDuitama
