{% set name = "decOM" %}
{% set version = "0.0.18" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f976a9b79e8810ee6609a93d1b09b835bd76b5aba82a1752c24e7fabdbc385c8

build:
  number: 0
  entry_points:
    - decOM=decOM.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - dask >=2021.12.0
    - importlib_resources >=5.4.0
    - python-kaleido
    - pip
    - plotly >=5.5.0
    - python
    - colorama
  run:
    - dask >=2021.12.0
    - importlib_resources >=5.4.0
    - python-kaleido
    - plotly >=5.5.0
    - python
    - colorama
test:
  imports:
    - decOM
    - decOM.data
    - decOM.modules
  commands:
    - decOM --help

about:
  home: "https://github.com/CamilaDuitama/decOM"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "decOM: K-mer method for aOral metagenome decontamination"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - CamilaDuitama
