{% set name = "decOM" %}
{% set version = "0.0.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e800149dcd19311923b842a56c52c345266115b26509f4b5bf52afaa50c1de53

build:
  number: 0
  entry_points:
    - decOM=decOM.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - dask >=2021.12.0
    - importlib_resources >=5.4.0
    - python-kaleido
    - pip
    - plotly >=5.5.0
    - python
    - kmtricks >=1.2.1
  run:
    - dask >=2021.12.0
    - importlib_resources >=5.4.0
    - python-kaleido
    - plotly >=5.5.0
    - python
    - kmtricks >=1.2.1

test:
  imports:
    - decOM
    - decOM.data
  commands:
    - decOM --help

about:
  home: "https://github.com/CamilaDuitama/decOM"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "decOM: K-mer method for aOral metagenome decontamination"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - #33686652
