{% set name = "decOM" %}
{% set version = "0.0.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 5a15e3d665830e5d23cdccefcca4cddcf9cf9df1ed6df0372d691967b67ffc41

build:
  number: 0
  entry_points:
    - decOM=decOM.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - dask >=2021.12.0
    - importlib_resources >=5.4.0
    - python-kaleido
    - pip
    - plotly >=5.5.0
    - python
  run:
    - dask >=2021.12.0
    - importlib_resources >=5.4.0
    - python-kaleido
    - plotly >=5.5.0
    - python

test:
  imports:
    - decOM
    - decOM.data
  commands:
    - decOM --help

about:
  home: "https://github.com/CamilaDuitama/decOM"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "decOM: K-mer method for aOral metagenome decontamination"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
