{% set name = "decOM" %}
{% set version = "0.0.25" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e8d8f76822c6f631c3ed10016193ad01a2b86ab31c6929b6af1fdfa1d3989efa

build:
  number: 0
  entry_points:
    - decOM = decOM.__main__:main
    - decOM-aOralOut = decOM.aOralOut.__main__:main
    - decOM-format = decOM.format.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - colorama
    - dask >=2021.12.0
    - importlib_resources >=5.4.0
    - python-kaleido
    - pip
    - plotly >=5.5.0
    - python
  run:
    - colorama
    - dask >=2021.12.0
    - importlib_resources >=5.4.0
    - python-kaleido
    - plotly >=5.5.0
    - python

test:
  imports:
    - decOM
    - decOM.aOralOut
    - decOM.data
    - decOM.format
    - decOM.modules
    - test
  commands:
    - decOM --help
    - decOM-aOralOut --help
    - decOM-format --help

about:
  home: "https://github.com/CamilaDuitama/decOM"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "decOM: Similarity-based microbial source tracking for contamination assessment of ancient oral samples using k-mer-based methods"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
